# Generated by Django 3.0.5 on 2020-04-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_mob', models.IntegerField()),
                ('customer_time', models.CharField(max_length=50)),
                ('customer_country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'enquiry',
                'managed': True,
            },
        ),
    ]
