# Generated by Django 3.0.5 on 2020-04-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='customer_mob',
            field=models.CharField(max_length=20),
        ),
    ]
